env:
  name: application-local.yml
  environment: test
  server: http://localhost/

spring:
  config:
    activate:
      on-profile: local

  #Database
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/minglespace
    username: sa
    password:

  #JPA Config
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 300

server:
  port: 80

